// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
     case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-uQAUF2wRHUADtqE9fCLRHZl9l8taK3o',
    appId: '1:15564026221:web:1f7e0c52db2f550422aa64',
    messagingSenderId: '15564026221',
    projectId: 'partnerup-2f6a8',
    authDomain: 'partnerup-2f6a8.firebaseapp.com',
    storageBucket: 'partnerup-2f6a8.firebasestorage.app',
    measurementId: 'G-6QNS770NHT',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAACXi8-oq7JECy4JPwZXRSCqaInUnFUyg',
    appId: '1:15564026221:android:d9ba1b2a9835db0c22aa64',
    messagingSenderId: '15564026221',
    projectId: 'partnerup-2f6a8',
    storageBucket: 'partnerup-2f6a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzFN1uBDeJD5wOgFEKlLlzuxYfuhCt-Ak',
    appId: '1:15564026221:ios:7685d81ff84edeb622aa64',
    messagingSenderId: '15564026221',
    projectId: 'partnerup-2f6a8',
    storageBucket: 'partnerup-2f6a8.firebasestorage.app',
    iosBundleId: 'com.example.partnerupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-uQAUF2wRHUADtqE9fCLRHZl9l8taK3o',
    appId: '1:15564026221:web:2655d8acbf1c559222aa64',
    messagingSenderId: '15564026221',
    projectId: 'partnerup-2f6a8',
    authDomain: 'partnerup-2f6a8.firebaseapp.com',
    storageBucket: 'partnerup-2f6a8.firebasestorage.app',
    measurementId: 'G-67VWWDQ3SF',
  );
}
